# Generated by Django 4.2.4 on 2023-08-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eng_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='jap_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
