# Generated by Django 4.2.4 on 2023-08-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_remove_pokemonentity_next_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_evolutions', to='pokemon_entities.post'),
        ),
    ]
