# Generated by Django 4.2.4 on 2023-08-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_remove_post_next_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_pokemon', to='pokemon_entities.post', verbose_name='Эволюцонировал из'),
        ),
    ]
