# Generated by Django 4.2.4 on 2023-08-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_alter_pokemonentity_pokemon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='attack',
            field=models.IntegerField(verbose_name='Атака'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='defense',
            field=models.IntegerField(verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='health',
            field=models.IntegerField(verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='level',
            field=models.IntegerField(verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='stamina',
            field=models.IntegerField(verbose_name='Стамина'),
        ),
    ]
